-- SYSTEM 계정에서 하셔야합니다 무조건 !!
CREATE USER SWM IDENTIFIED BY SWM;
-- SYSTEM 계정에서 하셔야합니다 무조건 !!
GRANT CONNECT, RESOURCE TO SWM;
-- 회원 디비
CREATE TABLE MEMBER (
    USERNO NUMBER PRIMARY KEY ,
    USERID VARCHAR2(30)  UNIQUE ,
    USERNAME VARCHAR2(20) NOT NULL,
    NICKNAME VARCHAR2(20) NOT NULL ,
    PASSWORD VARCHAR2(100) NOT NULL ,
    EMAIL VARCHAR2(30) NOT NULL , 
    PHONE1 VARCHAR2(20) NOT NULL , 
    PHONE2 VARCHAR2(20) NOT NULL , 
    PHONE3 VARCHAR2(20) NOT NULL , 
    STATUS CHAR DEFAULT 'N' CHECK(STATUS IN('Y','N')) 
);
SELECT * FROM MEETING;
COMMIT;
-- MEMBER 
-- USERNO 회원 번호
-- USERID 회원 아이디
-- USERNAME 회원 이름
-- NICKNAME 회원 닉네임
-- PASSWORD 회원 비밀번호
-- JUMIN 회원 주민번호
-- PHONE 회원 폰번호
-- STATUS 회원 탈퇴 상태


--회원번호 시퀀스
CREATE SEQUENCE SEQ_MEM; 


-- 스터디카페 디비
CREATE TABLE STUDYCAFE (
    STUDYCAFE_NO NUMBER PRIMARY KEY , 
    STUDYCAFE_NAME VARCHAR2(30) NOT NULL ,
    SYUDYCAFE_ADDRESS VARCHAR2(20) NOT NULL,
    STUDYCAFE_PHONE  VARCHAR2(30) NOT NULL ,
    STUDYCAFE_RUNTIME DATE NOT NULL ,
    STUDYCAFE_ROOMNO NUMBER ,
    STUDYCAFE_IMAGE VARCHAR2(2000) 
    ); 
    

-- STUDYCAFE_NO 스터디카페 번호
-- STUDYCAFE_NAME 스터디카페 이름
-- SYUDYCAFE_ADDRESS 스터디카페 주소
-- STUDYCAFE_PHONE 스터디카페 폰번호
-- STUDYCAFE_RUNTIME 스터디 카페 운영시간
-- STUDYCAFE_ROOMNO 스터디카페 방번호
-- STUDYCAFE_IMAGE 스터디카페 이미지


-- 스터디카페 번호 시퀀스
CREATE SEQUENCE SEQ_STUDYCAFE;


-- 스터디카페 예약테이블
CREATE TABLE STUDYCAFE_BOOK(
    BOOK_NO NUMBER PRIMARY KEY ,
    STUDYCAFE_NO NUMBER ,
    BOOKER_NO NUMBER ,
    STUDYCAFE_ROOMNO NUMBER , 
    BOOK_DATE DATE ,
    START_TIME DATE ,
    END_TIME DATE
);

-- BOOK_NO 예약 번호 
-- STUDYCAFE_NO 스터디카페 번호
-- BOOKER_NO  예약자 회원 번호
-- STUDYCAFE_ROOMNO 스터디카페 방번호
-- BOOK_DATE 예약날짜
-- START_TIME 예약 시작 시간
-- END_TIME 예약 종료 시간

-- 예약 시퀀스
CREATE SEQUENCE SEQ_BOOK_NO;

-- 모임 
CREATE TABLE MEETING (
    MEETING_NO NUMBER PRIMARY KEY ,
    MEETING_LEADER NUMBER ,
    MEETING_AGE VARCHAR2(20) ,
    MEETING_TITLE VARCHAR2(30) NOT NULL ,
    MEETING_CONTENT VARCHAR2(2000) NOT NULL ,
    MEETING_ADDRESS VARCHAR2(20) ,
    MEETING_SUBJECT VARCHAR2(20) ,
    MEETING_LIMIT NUMBER ,
    STATUS CHAR DEFAULT 'N' CHECK(STATUS IN('Y','N')),
    MEETING_DATE DATE DEFAULT SYSDATE
);

-- MEETING_NO 모임 게시글 번호
-- MEETING_LEADER 모임장 회원 번호
-- MEETING_AGE 모임 나이대
-- MEETING_TITLE 모임 게시글 제목
-- MEETING_CONTENT 모임 게시글 내용
-- MEETING_ADDRESS 모임 게시글 주소
-- MEETING_SUBJECT 모임 게시글 과목
-- MEETING_LIMIT 모임 게시글 모집인원
-- STATUS 모임 게시글 삭제 여부

-- 모임 게시글 시퀀스
CREATE SEQUENCE SEQ_MEETING;
SELECT * FROM MEETING_BOARD;

-- 모임 게시글 예약 디비
CREATE TABLE MEETING_PERMIT(
    MEETING_NO NUMBER  ,
    USERNO NUMBER ,
    ABOUTME VARCHAR2(200) ,
    PERMIT CHAR(1) DEFAULT 'N' CHECK(PERMIT IN('Y','N')) 
);
COMMIT;

-- 모임 내 게시글 
CREATE TABLE MEETING_BOARD (
    MEETING_BOARD_NO NUMBER PRIMARY KEY ,
    MEETING_NO NUMBER ,
    MEETING_BOARD_WRITER NUMBER ,
    MEETING_BOARD_TITLE VARCHAR2(30) NOT NULL ,
    MEETING_BOARD_CONTENT VARCHAR2(2000) NOT NULL ,
    MEETING_BOARD_DATE DATE DEFAULT SYSDATE ,
    MEETING_BOARD_HIT NUMBER ,
    STATUS CHAR DEFAULT 'N' CHECK(STATUS IN('Y','N'))
);

-- MEETING_BOARD_NO 모임 내 게시글 번호
-- MEETING_NO  모임 번호
-- MEETING_BOARD_WRITER  모임 내 게시글 작성자
-- MEETING_BOARD_TITLE  모임 내 게시 제목
-- MEETING_BOARD_CONTENT 모임 내 게시글 내용
-- MEETING_BOARD_DATE  모임 내 게시글 등록 날짜
-- MEETING_BOARD_HIT 모임 내 게시글 조회수
-- STATUS  모임 내 게시글 삭제 여부

-- 모임 내 게시글 시퀀스
CREATE SEQUENCE SEQ_MEETING_BOARD;

-- 모임 내 게시글 댓글 디비
CREATE TABLE MEETING_BOARD_COMMENT(
    MEETING_BOARD_COMMENT_NO NUMBER  PRIMARY KEY,
    MEETING_BOARD_NO NUMBER ,
    USERNO NUMBER ,
    MEETING_BOARD_COMMENT_CONTENT VARCHAR2(300) ,
    MEETING_BOARD_COMMENT_DATE DATE DEFAULT SYSDATE ,
    MEETING_BOARD_COMMENT_LEVEL NUMBER ,
    MEETING_BOARD_COMMENT_REFNO NUMBER ,
    STATUS CHAR DEFAULT 'N' CHECK(STATUS IN('Y','N'))
);

-- MEETING_BOARD_COMMENT_NO  모임 내 게시글 댓글 번호
-- MEETING_BOARD_NO 모임 게시글 번호
-- USERNO 댓글 쓴 회원 번호
-- MEETING_BOARD_COMMENT_CONTENT 모임 내 게시글 댓글 내용
-- MEETING_BOARD_COMMENT_DATE 모임 내 게시글 댓글 날짜
-- MEETING_BOARD_COMMENT_LEVEL 모임 내 게시글 댓글 레벨
-- MEETING_BOARD_COMMENT_REFNO 모임 내 게시글 참고 댓글 번호
-- STATUS 모임 내 게시글 댓글 삭제 여부

-- 모임 내 게시판 댓글 시퀀스
CREATE SEQUENCE SEQ_MEETING_BOARD_COMMENT;

-- 모임 내 게시판 파일
CREATE TABLE MEETING_BOARD_FILE ( 
IDX NUMBER, 
MEETING_BOARD_NO NUMBER NOT NULL, 
ORIGINAL_FILE_NAME VARCHAR2(260 BYTE) NOT NULL, 
STORED_FILE_NAME VARCHAR2(36 BYTE) NOT NULL, 
FILE_SIZE NUMBER, 
DEL_GB VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL, 
PRIMARY KEY (IDX) );

-- 자유 게시판
CREATE TABLE FREE_BOARD (
    FREE_NO NUMBER PRIMARY KEY ,
    USERNO NUMBER ,
    FREE_TITLE VARCHAR2(30) NOT NULL ,
    FREE_CONTENT VARCHAR2(3000) NOT NULL ,
    FREE_DATE DATE DEFAULT SYSDATE ,
    FREE_FILE VARCHAR2(2000) ,
    FREE_COUNT NUMBER ,
    STATUS CHAR DEFAULT 'N' CHECK(STATUS IN('Y','N')) 
);

-- FREE_NO 커뮤니티 게시글 번호
-- USERNO  회원 번호
-- FREE_TITLE 커뮤니티 게시글 제목
-- FREE_CONTENT  커뮤니티 게시글 내용
-- FREE_DATE  커뮤니티 게시글 등록 날짜
-- FREE_FILE  커뮤니티 게시글 파일
-- FREE_COUNT  커뮤니티 게시글 조회수
-- STATUS  커뮤니티 게시글 삭제 여부

-- 자유 게시판 시퀀스
CREATE SEQUENCE SEQ_FREE_BOARD;

-- 자유게시판 댓글
CREATE TABLE FREE_COMMENT(
    FREE_COMMENT_NO NUMBER  PRIMARY KEY,
    FREE_NO NUMBER ,
    USERNO NUMBER ,
    FREE_COMMENT_CONTENT VARCHAR2(300) ,
    FREE_COMMENT_DATE DATE DEFAULT SYSDATE ,
    FREE_COMMENT_LEVEL NUMBER ,
    FREE_COMMENT_REFNO NUMBER ,
    STATUS CHAR DEFAULT 'N' CHECK(STATUS IN('Y','N')) 
);

-- FREE_COMMENT_NO  자유 게시글 댓글 번호
-- FREE_NO 자유 게시글 번호
-- USERNO 자유 번호
-- FREE_COMMENT_CONTENT 자유 게시글 댓글 내용
-- FREE_COMMENT_DATE 자유 게시글 댓글 날짜
-- FREE_COMMENT_LEVEL 자유 게시글 댓글 레벨
-- FREE_COMMENT_REFNO 자유 게시글 참조할 댓글 번호
-- STATUS 자유 게시글 댓글 삭제 여부

-- 커뮤니티 게시판 댓글 번호
CREATE SEQUENCE SEQ_FREE_COMMENT;

-- 1:1 문의 테이블
CREATE TABLE ASK(
    ASK_NO NUMBER PRIMARY KEY ,
    USERNO NUMBER ,
    ASK_TITLE VARCHAR2(30) ,
    ASK_CONTENT VARCHAR2(300) ,
    ASK_DATE DATE DEFAULT SYSDATE
);

-- 1:1 문의 번호 시퀀스
CREATE SEQUENCE SEQ_ASK;

-- 1:1 문의 댓글 테이블
CREATE TABLE ASK_COMMENT(
    ASK_COMMENT_NO NUMBER PRIMARY KEY,
    ASK_NO NUMBER ,
    USERNO NUMBER ,
    ASK_COMMENT_CONTENT VARCHAR2(300) ,
    ASK_COMMENT_DATE DATE DEFAULT SYSDATE 
);

-- 괸리자 테이블
CREATE TABLE ADMIN (
    ADMIN_ID VARCHAR2(30) ,
    ADMIN_PASSWORD VARCHAR2(30)
);

--  신고회원 정보 테이블
CREATE TABLE REPORT(
    REPORT_NO NUMBER PRIMARY KEY ,
    REPORTER_NICKNAME VARCHAR2(30) NOT NULL ,
    REPORTED_NICKNAME VARCHAR2(30) NOT NULL ,
    REASON VARCHAR2(300) NOT NULL,
    REPORT_DATE DATE DEFAULT SYSDATE ,
    STATUS CHAR DEFAULT 'N' CHECK(STATUS IN('Y','N')) 
);
SELECT * FROM MEETING_PERMIT;


-- 지역 테이블
CREATE TABLE LOCATION(
    SI VARCHAR2(30) NOT NULL ,
    GU VARCHAR2(30) NOT NULL
);
    